### ISSUE TITLE
Questions about the exact features of fileshelter

### ISSUE THREAD

**Issue by ovizii** [epoupon/fileshelter#13]
I'm looking for something like fileshelter but am not sure it has the features I am looking for. Currently still comparing a few different projects.

Would it be possible to add IMAP as an authentication provider? That way I could easily give all existing users of an IMAP server access or is authentication meant to happen outside fileshelter?

How are uploaded files treated, are they encrypted? If yes. client-side or server-side?

**Comment by epoupon** [comment]
Hello,

Download: Fileshelter is designed to share files with any people that has an internet access.
The only things you have to know to download a file is an unique url and optionally a password.
Upload: There is an open feature request to request people to enter a password in order to upload a file, but there is no per user authentication planned.
I guess to can additionally ensure a user authentication on the upload page using a reverse proxy.

Encryption: as this project is meant to be self hosted, there is no encryption (except during transport thanks to tls). The main use is to send files or to receive files. You should not use a third party instance to send files that are considered private, unless you encrypt the files yourself.

**Comment by ovizii** [comment]
hi and thanks for the answer. You see, my thoughts were that if I make this self-hosted instance publicly available, I become liable for whatever content gets shared.

One way around that would be to make it only accessible to a specific user base but it sounds like I have to make use of authentication before a visitor accesses fileshelter if its not going to be built-in. 

The other way around would be to have client side encryption and absolutely no logging so at least as the host of this system I wouldn't be able to even know what files are being transferred or who uploaded and downloaded them.

**Comment by epoupon** [comment]
Hello,

As you said you are liable about the contents that get shared, that is why fileshelter provides a basic terms of service (that may me think there should be a mandatory checkbox each time somebody tries to upload a file in order to accept the tos)

About public restrictions the only built-in feature that is likely to be implemented shortly is the upload password required to share files. I guess it would not be enough for you?

I am not sure about the encryption/no log approach, as there are still legal issues about file sharing.

**Comment by ovizii** [comment]
Thanks for your feedback. I am no expert, I am just thinking out loud. 

I thought that if you make sure to not log and it is technically impossible for me as the service provider to know what files get shared I would not have to "enforce" it. So basically, yes, there are terms of service uploaders need to agree to but if the files, the file names, the metadata of files and their content are client-side encrypted and nothing is logged on the server, the only people knowing what was transferred would be the uploader and the downloader so even if there was some say illegal content I guess I would just have to make sure to remove it as that seems to be how sayNZB providers seem to be working. 

As I said, no expert here, just thinking out loudly and not asking you to change your product but I'd be very happy if you could point me towards any docs about how this is usually handled.
