### ISSUE TITLE
Build FileShelter binary packages for Debian Bullseye

### ISSUE THREAD

**Issue by mrrfv** [epoupon/fileshelter#66]
Binary packages for Debian 11 are not built, resulting in errors when trying to install the application on the latest Debian version (11 Bullseye).

**Comment by brammp** [comment]
Packages are seem to be available for Debian 11 (Bullseye),
Also domain seems to have changed form `debian.poupon.io` to `debian.poupon.dev`.

You can install the therepo using the following commands
```
wget -O - https://debian.poupon.dev/apt/debian/epoupon.gpg.key | apt-key add -
echo "deb https://debian.poupon.dev/apt/debian bullseye main" > /etc/apt/sources.list.d/epoupon.list
```
If you want to add the repo without apt-key (since it is deprecated)
make sure `gpg` `curl` and `ca-certificates` are installed, these are required for this methode to work

```
curl -L -s https://debian.poupon.dev/apt/debian/epoupon.gpg.key | gpg --dearmor > /usr/share/keyrings/epoupon-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/epoupon-keyring.gpg] https://debian.poupon.dev/apt/debian bullseye main" > /etc/apt/sources.list.d/epoupon.list
```
after running `apt update` fileshelter should be installable using `apt install fileshelter`
