### ISSUE TITLE
Display share URLs  when using fileshelter-list --details 

### ISSUE THREAD

**Issue by svalo** [epoupon/fileshelter#79]
When I manually create a share using `fileshelter-create` the command outputs only the share-id. In order to obtain the share URL I need to remember how to construct the full URL.

It would be nice for the command `fileshalter-list --details` to  be able to print something like:

Share URL: `http(s)://your.domain.tld/share-download/<share-id>` 

I'm aware that fileshelter invoked from CLI doesn't know the domain but I'd still find useful to have to only  replace `your.domain.tld` with the actual one instead of remembering the full URL.

Bonus would be to also print the `edit` URL but I get that it may not be desirable due to privacy concern.

**Comment by epoupon** [comment]
Hello! Maybe we could just provide the `fileshelter-list` an extra parameter with the deploy URL, so that we can generate the correct URLs. About the 'edit' URLs privacy concerns, `fileshelter-list` should already be run as admin (or as a user that has read/write accesses to the share database), so I guess it should be OK

**Comment by epoupon** [comment]
That s a good idea, but that deserves a separate issue.
We would want an unified `fileshelter-cmd` tool that can list, create and delete shares

**Comment by epoupon** [comment]
@b4444 : done in v6.0.0
